# Generated by Django 4.2 on 2023-04-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_user_post_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
