# Generated by Django 4.2 on 2023-06-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
