# Generated by Django 4.2 on 2023-06-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='account_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Image'),
        ),
    ]
