# Generated by Django 4.2 on 2023-06-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comment_account_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='account_image',
        ),
    ]
