# Generated by Django 4.2 on 2023-04-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=300, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=300, null=True, verbose_name='Number'),
        ),
    ]
